### ISSUE TITLE
Link to scaladoc is broken.

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [ist-dsi/akkastrator#3]
from https://github.com/ist-dsi/akkastrator/commit/cefe78f3d6950e10a5248396ef933ff58e8e569b

https://ist-dsi.github.io/akkastrator/latest/api/#pt.tecnico.dsi.akkastrator.package

this link will take me to a 404

**Comment by thomasdziedzic-pd** [comment]
Note that there are 2 links to the scaladoc. the badge and an actual text link. The badge is now fixed but the text link is still broken. `[Latest scaladoc documentation](https://ist-dsi.github.io/akkastrator/latest/api/pt/tecnico/dsi/akkastrator/index.html)`

**Comment by Lasering** [comment]
Is it obvious you can click in the Scaladocs badge to access them? If yes, I'll just remove the text link.

**Comment by thomasdziedzic-pd** [comment]
I clicked on the text link because it was bigger. I can definitely get used to clicking on the badge though.

One thing to note is that I usually search for "doc" on a page, and unfortunately the badge doesn't match it since it is an image. Other people might not be able to find the docs, but this could just be me :)

**Comment by Lasering** [comment]
Thanks for the input. I'll leave the text link.
